name: Selenium Automation Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python Dependencies
        run: |
          pip install selenium
          pip install webdriver-manager
          pip install pytest
          pip install pytest-html
          pip install requests

      - name: Clean pytest cache
        run: |
          find . -type d -name __pycache__ -exec rm -rf {} +
          find . -type f -name "*.pyc" -delete

      - name: Run Selenium Tests
        run: |
          pytest -v --html=report.html
